/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continuada01;

import java.util.Random;

/**
 *
 * @author mi1
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //Mexendo com o estilo da label
        lblValorCpu.setOpaque(true);
        lblValorMemoria.setOpaque(true);
        lblValorDisco.setOpaque(true);
        
        //Centralizando o frame na tela
        this.setLocationRelativeTo(null);
        
        //Setando o layout do Panel
        jPanel1.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblMaxDisco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMaxMemoria = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblRandomMemoria = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMinMemoria = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMediaMemoria = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblRandomCpu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMinCpu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblRandomDisco = new javax.swing.JLabel();
        lblMediaCpu = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        lblMaxCpu = new javax.swing.JLabel();
        lblMemoria1 = new javax.swing.JLabel();
        lblCpu2 = new javax.swing.JLabel();
        lblDisco1 = new javax.swing.JLabel();
        lblValorCpu = new javax.swing.JLabel();
        lblValorDisco = new javax.swing.JLabel();
        lblValorMemoria = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblMediaDisco = new javax.swing.JLabel();
        lblMediaCpu3 = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de tarefas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(39, 39, 54));
        jPanel1.setForeground(new java.awt.Color(173, 177, 179));

        lblMaxDisco.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMaxDisco.setForeground(new java.awt.Color(173, 177, 179));
        lblMaxDisco.setText("0");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(173, 177, 179));
        jLabel12.setText("Máximo:");

        lblMaxMemoria.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMaxMemoria.setForeground(new java.awt.Color(173, 177, 179));
        lblMaxMemoria.setText("0");

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(173, 177, 179));
        jLabel24.setText("Máximo:");

        lblRandomMemoria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblRandomMemoria.setForeground(new java.awt.Color(173, 177, 179));
        lblRandomMemoria.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(173, 177, 179));
        jLabel7.setText("Uso de Disco:");

        lblMinMemoria.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMinMemoria.setForeground(new java.awt.Color(173, 177, 179));
        lblMinMemoria.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(173, 177, 179));
        jLabel8.setText("Mínimo:");

        lblMediaMemoria.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMediaMemoria.setForeground(new java.awt.Color(173, 177, 179));
        lblMediaMemoria.setText("0");

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(173, 177, 179));
        jLabel25.setText("Média:");

        lblRandomCpu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblRandomCpu.setForeground(new java.awt.Color(173, 177, 179));
        lblRandomCpu.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(173, 177, 179));
        jLabel9.setText("Uso de CPU:");

        lblMinCpu.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMinCpu.setForeground(new java.awt.Color(173, 177, 179));
        lblMinCpu.setText("0");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(173, 177, 179));
        jLabel13.setText("Mínimo:");

        lblRandomDisco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblRandomDisco.setForeground(new java.awt.Color(173, 177, 179));
        lblRandomDisco.setText("0");

        lblMediaCpu.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMediaCpu.setForeground(new java.awt.Color(173, 177, 179));
        lblMediaCpu.setText("0");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(173, 177, 179));
        jLabel14.setText("Uso de Disco:");

        jLabel100.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(173, 177, 179));
        jLabel100.setText("Média:");

        lblMaxCpu.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMaxCpu.setForeground(new java.awt.Color(173, 177, 179));
        lblMaxCpu.setText("0");

        lblMemoria1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblMemoria1.setForeground(new java.awt.Color(192, 12, 39));
        lblMemoria1.setText("Memória");

        lblCpu2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblCpu2.setForeground(new java.awt.Color(192, 12, 39));
        lblCpu2.setText("CPU");

        lblDisco1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblDisco1.setForeground(new java.awt.Color(192, 12, 39));
        lblDisco1.setText("Disco");

        lblValorCpu.setBackground(new java.awt.Color(192, 12, 39));

        lblValorDisco.setBackground(new java.awt.Color(192, 12, 39));

        lblValorMemoria.setBackground(new java.awt.Color(192, 12, 39));

        lblMinDisco.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMinDisco.setForeground(new java.awt.Color(173, 177, 179));
        lblMinDisco.setText("0");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(173, 177, 179));
        jLabel15.setText("Mínimo:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(173, 177, 179));
        jLabel16.setText("Máximo:");

        lblMediaDisco.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMediaDisco.setForeground(new java.awt.Color(173, 177, 179));
        lblMediaDisco.setText("0");

        lblMediaCpu3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblMediaCpu3.setForeground(new java.awt.Color(173, 177, 179));
        lblMediaCpu3.setText("Média:");

        jButton.setBackground(new java.awt.Color(153, 153, 153));
        jButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButton.setBorder(null);
        jButton.setFocusPainted(false);
        jButton.setFocusable(false);
        jButton.setLabel("Gerenciar recursos");
        jButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Aharoni", 0, 32)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle1.setText("Gerenciador de tarefas");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(173, 177, 179));
        jLabel1.setText("MB");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 177, 179));
        jLabel2.setText("MB");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(173, 177, 179));
        jLabel3.setText("MB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorMemoria)
                            .addComponent(lblValorDisco)
                            .addComponent(lblValorCpu)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMediaCpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMediaDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRandomMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(lblMemoria1)
                                    .addComponent(lblDisco1)
                                    .addComponent(lblCpu2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(119, 119, 119)
                                                .addComponent(lblMediaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addComponent(lblMaxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblRandomCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRandomDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMinCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMinMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMediaMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMaxMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 187, Short.MAX_VALUE)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblCpu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRandomCpu)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinCpu)
                    .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMediaCpu)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxCpu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorCpu)
                .addGap(51, 51, 51)
                .addComponent(lblDisco1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRandomDisco)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinDisco)
                    .addComponent(lblMediaCpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMediaDisco)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxDisco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorDisco)
                .addGap(51, 51, 51)
                .addComponent(lblMemoria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRandomMemoria)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinMemoria)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMediaMemoria)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorMemoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    Integer minCpu, minDisco, minMemoria, maxMemoria, maxDisco, maxCpu;
    
    Integer valueCpu, valueDisco, valueMemoria;
    
    Integer contador = 1;

    
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        //Sorteando valores aleatórios do tipo INT
        valueCpu = new Random().nextInt(100) + 1;
        valueDisco = new Random().nextInt(500) + 1;
        valueMemoria = new Random().nextInt(80) + 1;
        //Fim
        
        //Chamando as funções de funcionalidades
        mudaWidth();
        mudaTexto();
        mediaValores();
        //Fim
        
        //Incrementando o contador
        contador++;
    }//GEN-LAST:event_jButtonActionPerformed
      
    private void mudaWidth(){
        //Setando WIDTH das label's com os valores sorteados
        //Setando eixos x e y e heigth
        lblValorCpu.setSize(Integer.valueOf(valueCpu),32);
        lblValorDisco.setSize(Integer.valueOf(valueDisco),32);
        lblValorMemoria.setSize(Integer.valueOf(valueMemoria),32);
        //Fim   
    }
    
    private void mudaTexto(){
        //Inicializando as variáveis e setando o texto das label's
        if(contador == 1){
            minCpu = valueCpu;
            maxCpu = valueCpu;
           
            minDisco = valueDisco;
            maxDisco = valueDisco;
            
            maxMemoria = valueMemoria;
            minMemoria = valueMemoria;
            
            lblMaxCpu.setText(String.valueOf(maxCpu));
            lblMinCpu.setText(String.valueOf(minCpu));
            
            lblMaxDisco.setText(String.valueOf(maxDisco));
            lblMinDisco.setText(String.valueOf(minDisco));
            
            lblMaxMemoria.setText(String.valueOf(maxMemoria));
            lblMinMemoria.setText(String.valueOf(minMemoria));
            //Fim
        }else{
            //Comparando os valores para encontrar o méximo e o mínimo entre eles
            //CPU
            if(valueCpu>maxCpu){
                maxCpu = valueCpu;
                lblMaxCpu.setText(String.valueOf(maxCpu));
            }else if(valueCpu<minCpu){
                minCpu = valueCpu;
                lblMinCpu.setText(String.valueOf(minCpu));
            }
            
            //DISCO
            if(valueDisco>maxDisco){
                maxDisco = valueDisco;
                lblMaxDisco.setText(String.valueOf(maxDisco));
            }else if(valueDisco<minDisco){
                minDisco = valueDisco;
                lblMinDisco.setText(String.valueOf(minDisco));
            }
            
            //MEMORIA
            if(valueMemoria>maxMemoria){
                maxMemoria = valueMemoria;
                lblMaxMemoria.setText(String.valueOf(maxMemoria));
            }else if(valueMemoria<minMemoria){
                minMemoria = valueMemoria;
                lblMaxMemoria.setText(String.valueOf(minMemoria));
            }
        }
        
        //Apresentando os valores sorteados de cada recurso em sua respectiva label;
        //Convertendo os valores integers sorteados para string
        lblRandomCpu.setText(String.valueOf(valueCpu) );
        lblRandomDisco.setText(String.valueOf(valueDisco));
        lblRandomMemoria.setText(String.valueOf(valueMemoria));
        //Fim
        
    }
         

    //Declarando variáveis para a comparação de valor MÉDIO
    //MEDIA
         Integer mediaCpu = 0;
         Integer mediaMemoria = 0;
         Integer mediaDisco = 0;
    //Fim
         
    private void mediaValores(){
             mediaCpu = (mediaCpu + valueCpu);
             mediaMemoria = (mediaMemoria + valueMemoria);
             mediaDisco = (mediaDisco + valueDisco);
        
             lblMediaCpu.setText(String.valueOf(mediaCpu/contador));
             lblMediaMemoria.setText(String.valueOf(mediaMemoria/contador));
             lblMediaDisco.setText(String.valueOf(mediaDisco/contador));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCpu2;
    private javax.swing.JLabel lblDisco1;
    private javax.swing.JLabel lblMaxCpu;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxMemoria;
    private javax.swing.JLabel lblMediaCpu;
    private javax.swing.JLabel lblMediaCpu3;
    private javax.swing.JLabel lblMediaDisco;
    private javax.swing.JLabel lblMediaMemoria;
    private javax.swing.JLabel lblMemoria1;
    private javax.swing.JLabel lblMinCpu;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinMemoria;
    private javax.swing.JLabel lblRandomCpu;
    private javax.swing.JLabel lblRandomDisco;
    private javax.swing.JLabel lblRandomMemoria;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblValorCpu;
    private javax.swing.JLabel lblValorDisco;
    private javax.swing.JLabel lblValorMemoria;
    // End of variables declaration//GEN-END:variables

}
